# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

permissions:
  contents: read
  pull-requests: write

env:
  CG_EXEC: ionice -c 2 -n 2 nice -n 19

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install PNPM
        uses: step-security/action-setup@598c7206e1c7d361165e303487aa7772566a8e05 # v4.1.0
        with:
          version: 9.15.5

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
          cache: pnpm

      - name: Create env file
        run: |
          touch .env
          echo OPERATOR_KEY="0xa608e2130a0a3cb34f86e757303c862bee353d9ab77ba4387ec084f881d420d4" >> .env
          echo OPERATOR_ID="0.0.1022" >> .env
          echo HEDERA_NETWORK="local-node" >> .env
          cat .env

      - name: Start the local node
        id: start-local-node
        run: |
          ${{ env.CG_EXEC }} npx @hashgraph/hedera-local start -d --network local --balance=100000 --network-tag=0.63.7
          # Wait for the network to fully start
          sleep 30

      - name: Build with Maven
        env:
          spring_profiles_active: local-node
          HEDERA_ACCOUNT_ID: "0.0.1022"
          HEDERA_PRIVATE_KEY: "0xa608e2130a0a3cb34f86e757303c862bee353d9ab77ba4387ec084f881d420d4"
          HEDERA_NETWORK: local-node
        run: ./mvnw verify

      - name: Stop the local node
        id: stop-local-node
        if: ${{ steps.start-local-node.conclusion == 'success' && !cancelled() && always() }}
        run: ${{ env.CG_EXEC }} npx @hashgraph/hedera-local stop
